version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:3.0.0-node
        environment:
          RAILS_ENV: test
          DATABASE_HOST: 127.0.0.1 
      - image: circleci/postgres:13.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: true
          POSTGRES_DB: myapp_test
    working_directory: ~/myapp
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker run -d --name db company/proprietary-db:1.2.3
      - run:
          name: "bundle install"
          command: bundle install --path vendor/bundle
      # DBと接続できるまで待ちます
      - run:
          name: "waiting DB start"
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: "initialize DB"
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec

workflows:
  version: 2
  workflows:
    jobs:
      - test
