version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:3.0.0-rc1-buster-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_HOST: 127.0.0.1 
      - image: circleci/postgres:13.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
    working_directory: ~/myapp
    steps:
      - checkout
      - run:
          name: "bundle install"
          # command: bundle config set --local path 'vendor/bundle'
          command: bundle install --path vendor/bundle
      # DBと接続できるまで待ちます
      - run:
          name: "waiting DB start"
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 30s
      - run:
          name: "initialize DB"
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec

workflows:
  version: 2
  workflows:
    jobs:
      - test
